version: '2'
catalog:
  name: "GL Stack"
  version: "v0.1"
  description: "Gluster based NGINX and PHP"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: GLUSTER_PEER
      description: "GLUSTER_PEER"
      label: "GLUSTER_PEER (no HTTP)"
      required: true
      default: "gluster"
      type: "string"
    - variable: HTTP_GIT_SRC
      description: "GIT source"
      label: "GIT source"
      required: true
      default: "https://github.com/banago/simple-php-website.git"
      type: "string"
    - variable: HTTP_SITE_NAME
      description: "Site Name"
      label: "Site Name"
      required: true
      default: "testphp"
      type: "string"
services:
  gluster:
    scale: 2
    start_on_create: true
  wwwapp-lb:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: http
        service: wwwapp
        source_port: 80
        target_port: 80
      - priority: 2
        protocol: http
        service: wwwapp
        source_port: 443
        target_port: 443
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  wwwapp:
    scale: 1
    start_on_create: true
