version: '2'
catalog:
  name: "WP Stack"
  version: "v0.1"
  description: "WordPress Stack"
  minimum_rancher_version: v0.51.0
  questions:
    - variable: WP_URL
      description: "WordPress URL"
      label: "WordPress URL (no HTTP)"
      required: true
      default: ""
      type: "string"
    - variable: WP_URL2
      description: "WordPress URL 2"
      label: "WordPress URL (no HTTP) 2"
      required: true
      default: ""
      type: "string"
    - variable: WP_URL3
      description: "WordPress URL 3"
      label: "WordPress URL (no HTTP) 3"
      required: true
      default: ""
      type: "string"
    - variable: WP_URL4
      description: "WordPress URL 4"
      label: "WordPress URL (no HTTP) 4"
      required: true
      default: ""
      type: "string"
    - variable: WP_URL5
      description: "WordPress URL 5"
      label: "WordPress URL (no HTTP) 5"
      required: true
      default: ""
      type: "string"
    - variable: DOMAIN
      description: "Domain Name"
      label: "Domain Name"
      required: true
      default: ""
      type: "string"
    - variable: CLIENT
      description: "Client Name"
      label: "Client Name"
      required: true
      default: ""
      type: "string"
    - variable: WP_EMAIL
      description: "WordPress Email"
      label: "WP Email"
      required: true
      default: ""
      type: "string"
    - variable: EMAIL_USER
      description: "Email User"
      label: "Email User"
      required: true
      default: ""
      type: "string"
    - variable: EMAIL_SERVER
      description: "Email Server"
      label: "Email Server"
      required: true
      default: "mail.gandi.net"
      type: "string"
    - variable: EMAIL_PORT
      description: "Email Port"
      label: "Email Port"
      required: true
      default: "587"
      type: "string"
    - variable: EMAIL_FROM
      description: "Email FROM"
      label: "Email FROM"
      required: true
      default: ""
      type: "string"
services:
  phpmyadmin:
    scale: 1
    start_on_create: true
  pydio:
    scale: 1
    start_on_create: true
  nginx:
    scale: 1
    start_on_create: true
  nginx2:
    scale: 1
    start_on_create: true
  nginx3:
    scale: 1
    start_on_create: true
  nginx4:
    scale: 1
    start_on_create: true
  nginx5:
    scale: 1
    start_on_create: true
  wordpress:
    retain_ip: true
    scale: 1
    start_on_create: true
  wordpress2:
    retain_ip: true
    scale: 1
    start_on_create: true
  wordpress3:
    retain_ip: true
    scale: 1
    start_on_create: true
  wordpress4:
    retain_ip: true
    scale: 1
    start_on_create: true
  wordpress5:
    retain_ip: true
    scale: 1
    start_on_create: true
  LB:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      config: |-
        frontend 80
        acl lepath path_beg -i /.well-known/acme-challenge
        redirect scheme https code 302 if  !lepath !{ ssl_fc }
      port_rules:
      - hostname: '*.${DOMAIN}'
        priority: 1
        protocol: http
        service: letsencrypt
        source_port: 80
        target_port: 80
      - hostname: ${WP_URL}
        priority: 2
        protocol: https
        service: nginx
        source_port: 443
        target_port: 80
      - hostname: ${WP_URL2}
        priority: 3
        protocol: https
        service: nginx2
        source_port: 443
        target_port: 80
      - hostname: ${WP_URL3}
        priority: 4
        protocol: https
        service: nginx3
        source_port: 443
        target_port: 80
      - hostname: ${WP_URL4}
        priority: 5
        protocol: https
        service: nginx4
        source_port: 443
        target_port: 80
      - hostname: ${WP_URL5}
        priority: 6
        protocol: https
        service: nginx5
        source_port: 443
        target_port: 80
      - hostname: files.${DOMAIN}
        priority: 7
        protocol: https
        service: pydio
        source_port: 443
        target_port: 80
      - hostname: db.${DOMAIN}
        priority: 8
        protocol: https
        service: phpmyadmin
        source_port: 443
        target_port: 80
      - priority: 9
        protocol: tcp
        service: sftp
        source_port: 2222
        target_port: 22
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 60000
  mysql:
    scale: 1
    start_on_create: true
  mysql-backup:
    scale: 1
    start_on_create: true
  sftp:
    scale: 1
    start_on_create: true
  letsencrypt:
    scale: 1
    start_on_create: true
  redis:
    scale: 1
    start_on_create: true
