version: '2'
services:
  glusterfs-peer:
    image: rancher/glusterfs:v0.1.3
    network_mode: container:glusterfs-server
    volumes_from:
    - glusterfs-data
    command:
    - /opt/rancher/peerprobe.sh
    labels:
      io.rancher.container.hostname_override: container_name
  glusterfs-volume-create:
    image: rancher/glusterfs:v0.1.3
    network_mode: container:glusterfs-server
    volumes_from:
    - glusterfs-data
    command:
    - /opt/rancher/replicated_volume_create.sh
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  glusterfs-data:
    image: rancher/glusterfs:v0.1.3
    network_mode: none
    volumes:
    - /var/run
    command:
    - /bin/true
    labels:
      io.rancher.container.start_once: 'true'
      io.rancher.container.hostname_override: container_name
  glusterfs-server:
    cap_add:
    - SYS_ADMIN
    image: rancher/glusterfs:v0.1.3
    devices:
    - /dev/fuse:/dev/fuse:rwm
    volumes_from:
    - glusterfs-data
    command:
    - glusterd
    - -p
    - /var/run/gluster.pid
    - -N
    labels:
      io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/glusterfs-server
      io.rancher.sidekicks: glusterfs-peer,glusterfs-data,glusterfs-volume-create
      io.rancher.container.hostname_override: container_name