version: '2'
catalog:
  name: "Glusterfs"
  version: "v0.1.3"
  description: "Gluster fs"
  minimum_rancher_version: v0.51.0
  questions:
services:
  glusterfs-server:
  scale: 3
  metadata:
    volume_name: "ranchervol"
