version: '2'
catalog:
  name: "Glusterfs"
  version: "v0.1.3"
  description: "Gluster fs"
  minimum_rancher_version: v0.51.0
  questions:
      variable: HTTP_SITE_NAME
      description: "Site Name"
      label: "Site Name"
      required: true
      default: "www"
      type: "string"
services:
  glusterfs-peer:
    metadata:
      volume_name: ranchervol
    scale: 3
    start_on_create: true
  glusterfs-volume-create:
    metadata:
      volume_name: ranchervol
    scale: 3
    start_on_create: true
  glusterfs-data:
    metadata:
      volume_name: ranchervol
    scale: 3
    start_on_create: true
  glusterfs-server:
    metadata:
      volume_name: ranchervol
    scale: 3
    start_on_create: true