version: '2'
catalog:
  name: "Glusterfs"
  version: "v0.1.3"
  description: "Gluster fs"
  minimum_rancher_version: v0.51.0
  questions:
      variable: HTTP_SITE_NAME
      description: "Site Name"
      label: "Site Name"
      required: true
      default: "www"
      type: "string"
services:
  glusterfs-server:
  scale: 3
  metadata:
    volume_name: "ranchervol"
